### ISSUE TITLE
Developer Quickstart is broken

### ISSUE THREAD

**Issue by MarkSwanson** [vmware/haret#139]
I feel like I missed something, but I'm starting at the 'Start here if you are looking to hack on haret.'...

I'm stuck on the 'make launch' step:
haret/haret$ cd haret && make launch
-bash: cd: haret: No such file or directory

In case I was in the wrong dir, I tried from the git root for haret:
haret$ make launch
killall haret; exit 0
haret: no process found
cd dev/dev1; \
	  ./haret & \
	  echo $! > haret.pid
/bin/bash: line 0: cd: dev/dev1: No such file or directory
/bin/bash: line 1: ./haret: Is a directory
cd dev/dev2; \
	  ./haret & \
	  echo $! > haret.pid
/bin/bash: line 0: cd: dev/dev2: No such file or directory
cd dev/dev3; \
	  ./haret & \
	  echo $! > haret.pid
/bin/bash: line 1: ./haret: Is a directory
/bin/bash: line 0: cd: dev/dev3: No such file or directory
/bin/bash: line 1: ./haret: Is a directory

Please help me get started.
Thanks!

**Comment by MarkSwanson** [comment]
It looks like a step is missed:
make devrel
make launch then works without error.

**Comment by andrewjstone** [comment]
Hi @MarkSwanson, sorry for the confusion. It appears I broke this a while back when I removed the Makefile dependency for `devrel` on launch. I did this because haret now persists some data to disk and I didn't want it to be wiped out on each launch. Thanks for the heads up. I have fixed the README to reflect this change.
